model:
  name: SVSSM
  T: 4
  depths: [2, 4, 6, 2]
  dims: 64
  drop_path_rate: 0.2 
  patch_size: 4
  in_chans: 3
  num_classes: 100 
  patch_norm: True
  norm_layer: "ln2d" 
  use_checkpoint: False 
  imgsize: 224

exp:
  task_name: SVSSM_mini_imagenet
  model: SVSSM
  dataset: mini-imagenet
  root_path: ./data/Mini-ImageNet-Dataset
  img_size: 224
  batch_size: 16
  lr: 0.001
  epoch: 300
  weight_decay: 0.00001
  label_smoothing: 0.1
  warmup_epochs: 10
  use_ema: True
  use_clip_norm: True
  seed: 42
  pretrained: False
  checkpoint: ./checkpoints/20250707-183858_VMamba_mini_imagenet_VMamba_mini-imagenet_best.pth